name: Xcode Coverage Conversion
description: Converts Xcode code coverage files for processing with e.g. codecov.
author: ser.soft GmbH
inputs:
  derived-data:
    description: The path to Xcode's Derived Data folder.
    required: true
    default: '$HOME/Library/Developer/Xcode/DerivedData'
  output:
    description: The path to the output folder to put the converted coverage files in.
    required: true
    default: './.xcodecov'
runs:
  using: node12
  main: dist/index.js
branding:
  color: gray-dark
  icon: refresh-cw
